@baseUrl = http://localhost:3000/api
@resourceName=dataDebts

# @name getAll
GET {{baseUrl}}/{{resourceName}}

###

# @name pagination

GET {{baseUrl}}/{{resourceName}}?_page=2&_limit=10

###

# @name sort
GET {{baseUrl}}/{{resourceName}}?_sort=interestRate&_order=asc

###


# @name addNew
POST {{baseUrl}}/{{resourceName}}
Content-Type: application/json

{
  "name": "Hello world"
}

###

# @name update
PATCH {{baseUrl}}/{{resourceName}}/3
Content-Type: application/json

{
  "name": "new "
}


###

# @name Remove
DELETE {{baseUrl}}/{{resourceName}}/3

